# Release to PyPI using Trusted Publishing
# This workflow is triggered when a release is published on GitHub.
#
# https://docs.pypi.org/trusted-publishers/
# https://docs.pypi.org/trusted-publishers/adding-a-publisher/
# https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/
# https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/manage-environments

name: Release

on:
  release:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
    types: [released, prereleased]

jobs:
  release:
    # Release
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: pypi-release
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v6

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: 'pyproject.toml' # Read the Python version from the pyproject.toml file

      # Install Tools
      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade setuptools wheel

      # Build Package
      - name: Package
        run: |
          python -m build

      # Add Assets to Release on GitHub
      - name: Add Assets to Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # The name of the file(s) to upload
          files: |
            dist/*

      # Publish to PyPI using Trusted Publishing
      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
